"""Seed data for the in-memory SAP stand-in (see app/services/documents.py).

TEMPORARY: ported verbatim from the app's former local mocks so the UI looks
identical while SAP is unreachable. Delete this module when the real SAP read
services land. Keys are camelCase on purpose — they are validated through the
CamelModel aliases, mirroring exactly what SAP-mapped payloads will produce.
"""

RAW_PRE_ESTIMATES: list[dict] = [
    {
        "id": "PE-001",
        "projectId": "PRY-101",
        "projectName": "Torre Reforma 500",
        "supplierId": "PROV-01",
        "supplierName": "Constructora del Valle S.A. de C.V.",
        "amount": "1250000.00",
        "date": "2026-05-20T10:30:00Z",
        "status": "sin_autorizacion",
        "authorizationSteps": [
            {
                "userId": "USR-001",
                "userName": "Carlos Mendoza",
                "status": "sin_autorizacion",
                "date": None,
            },
            {
                "userId": "USR-002",
                "userName": "Ana Lucía Garza",
                "status": "sin_autorizacion",
                "date": None,
            },
        ],
    },
    {
        "id": "PE-002",
        "projectId": "PRY-101",
        "projectName": "Torre Reforma 500",
        "supplierId": "PROV-02",
        "supplierName": "Aceros y Materiales Monterrey",
        "amount": "875430.50",
        "date": "2026-05-18T14:00:00Z",
        "status": "autorizada_parcialmente",
        "authorizationSteps": [
            {
                "userId": "USR-001",
                "userName": "Carlos Mendoza",
                "status": "autorizada",
                "date": "2026-05-19T09:15:00Z",
            },
            {
                "userId": "USR-002",
                "userName": "Ana Lucía Garza",
                "status": "sin_autorizacion",
                "date": None,
            },
        ],
    },
    {
        "id": "PE-003",
        "projectId": "PRY-102",
        "projectName": "Residencial Bosques",
        "supplierId": "PROV-03",
        "supplierName": "Instalaciones Eléctricas MX",
        "amount": "340000.00",
        "date": "2026-05-15T08:00:00Z",
        "status": "autorizada",
        "authorizationSteps": [
            {
                "userId": "USR-001",
                "userName": "Carlos Mendoza",
                "status": "autorizada",
                "date": "2026-05-16T11:20:00Z",
            },
            {
                "userId": "USR-002",
                "userName": "Ana Lucía Garza",
                "status": "autorizada",
                "date": "2026-05-17T09:45:00Z",
            },
        ],
    },
    {
        "id": "PE-004",
        "projectId": "PRY-102",
        "projectName": "Residencial Bosques",
        "supplierId": "PROV-04",
        "supplierName": "Plomería Industrial del Norte",
        "amount": "520000.00",
        "date": "2026-05-14T16:30:00Z",
        "status": "rechazada",
        "authorizationSteps": [
            {
                "userId": "USR-001",
                "userName": "Carlos Mendoza",
                "status": "rechazada",
                "date": "2026-05-15T10:00:00Z",
                "comment": "Monto excede el presupuesto asignado para esta partida. "
                "Solicitar ajuste.",
            },
        ],
    },
    {
        "id": "PE-005",
        "projectId": "PRY-103",
        "projectName": "Centro Comercial Satélite",
        "supplierId": "PROV-01",
        "supplierName": "Constructora del Valle S.A. de C.V.",
        "amount": "2100000.00",
        "date": "2026-05-10T09:00:00Z",
        "status": "recepcionada",
        "authorizationSteps": [
            {
                "userId": "USR-001",
                "userName": "Carlos Mendoza",
                "status": "autorizada",
                "date": "2026-05-11T08:30:00Z",
            },
            {
                "userId": "USR-002",
                "userName": "Ana Lucía Garza",
                "status": "autorizada",
                "date": "2026-05-12T14:00:00Z",
            },
            {
                "userId": "USR-003",
                "userName": "Roberto Sánchez",
                "status": "autorizada",
                "date": "2026-05-13T10:15:00Z",
            },
        ],
    },
    {
        "id": "PE-006",
        "projectId": "PRY-101",
        "projectName": "Torre Reforma 500",
        "supplierId": "PROV-05",
        "supplierName": "Vidrios y Cancelería Moderna",
        "amount": "680000.00",
        "date": "2026-05-22T11:00:00Z",
        "status": "sin_autorizacion",
        "authorizationSteps": [
            {
                "userId": "USR-001",
                "userName": "Carlos Mendoza",
                "status": "sin_autorizacion",
                "date": None,
            },
            {
                "userId": "USR-003",
                "userName": "Roberto Sánchez",
                "status": "sin_autorizacion",
                "date": None,
            },
        ],
    },
    {
        "id": "PE-007",
        "projectId": "PRY-103",
        "projectName": "Centro Comercial Satélite",
        "supplierId": "PROV-02",
        "supplierName": "Aceros y Materiales Monterrey",
        "amount": "1450000.00",
        "date": "2026-05-21T13:45:00Z",
        "status": "autorizada_parcialmente",
        "authorizationSteps": [
            {
                "userId": "USR-002",
                "userName": "Ana Lucía Garza",
                "status": "autorizada",
                "date": "2026-05-22T08:00:00Z",
            },
            {
                "userId": "USR-003",
                "userName": "Roberto Sánchez",
                "status": "sin_autorizacion",
                "date": None,
            },
        ],
    },
    {
        "id": "PE-008",
        "projectId": "PRY-102",
        "projectName": "Residencial Bosques",
        "supplierId": "PROV-06",
        "supplierName": "Impermeabilizantes Nacionales",
        "amount": "195000.00",
        "date": "2026-05-23T15:30:00Z",
        "status": "sin_autorizacion",
        "authorizationSteps": [
            {
                "userId": "USR-001",
                "userName": "Carlos Mendoza",
                "status": "sin_autorizacion",
                "date": None,
            },
        ],
    },
]

RAW_ESTIMATES: list[dict] = [
    {
        "id": "EST-001",
        "projectId": "PRY-101",
        "projectName": "Torre Reforma 500",
        "supplierId": "PROV-01",
        "supplierName": "Constructora del Valle S.A. de C.V.",
        "concept": "Obra civil — cimentación profunda",
        "grossAmount": "3500000.00",
        "amortization": "350000.00",
        "guaranteeFund": "175000.00",
        "netAmount": "2975000.00",
        "date": "2026-05-19T09:00:00Z",
        "status": "sin_autorizacion",
        "contractProgress": {
            "totalAmount": "25000000.00",
            "exercisedAmount": "8750000.00",
            "remainingAmount": "16250000.00",
            "percentage": 35,
        },
        "authorizationSteps": [
            {
                "userId": "USR-001",
                "userName": "Carlos Mendoza",
                "status": "sin_autorizacion",
                "date": None,
            },
            {
                "userId": "USR-002",
                "userName": "Ana Lucía Garza",
                "status": "sin_autorizacion",
                "date": None,
            },
            {
                "userId": "USR-003",
                "userName": "Roberto Sánchez",
                "status": "sin_autorizacion",
                "date": None,
            },
        ],
    },
    {
        "id": "EST-002",
        "projectId": "PRY-101",
        "projectName": "Torre Reforma 500",
        "supplierId": "PROV-02",
        "supplierName": "Aceros y Materiales Monterrey",
        "concept": "Suministro de acero estructural",
        "grossAmount": "1800000.00",
        "amortization": "180000.00",
        "guaranteeFund": "90000.00",
        "netAmount": "1530000.00",
        "date": "2026-05-17T11:30:00Z",
        "status": "autorizada_parcialmente",
        "contractProgress": {
            "totalAmount": "12000000.00",
            "exercisedAmount": "7200000.00",
            "remainingAmount": "4800000.00",
            "percentage": 60,
        },
        "authorizationSteps": [
            {
                "userId": "USR-001",
                "userName": "Carlos Mendoza",
                "status": "autorizada",
                "date": "2026-05-18T08:45:00Z",
            },
            {
                "userId": "USR-002",
                "userName": "Ana Lucía Garza",
                "status": "sin_autorizacion",
                "date": None,
            },
        ],
    },
    {
        "id": "EST-003",
        "projectId": "PRY-102",
        "projectName": "Residencial Bosques",
        "supplierId": "PROV-03",
        "supplierName": "Instalaciones Eléctricas MX",
        "concept": "Instalación eléctrica — fase 2",
        "grossAmount": "950000.00",
        "amortization": "95000.00",
        "guaranteeFund": "47500.00",
        "netAmount": "807500.00",
        "date": "2026-05-12T14:00:00Z",
        "status": "autorizada",
        "contractProgress": {
            "totalAmount": "5800000.00",
            "exercisedAmount": "4350000.00",
            "remainingAmount": "1450000.00",
            "percentage": 75,
        },
        "authorizationSteps": [
            {
                "userId": "USR-001",
                "userName": "Carlos Mendoza",
                "status": "autorizada",
                "date": "2026-05-13T09:00:00Z",
            },
            {
                "userId": "USR-002",
                "userName": "Ana Lucía Garza",
                "status": "autorizada",
                "date": "2026-05-14T16:30:00Z",
            },
        ],
    },
    {
        "id": "EST-004",
        "projectId": "PRY-103",
        "projectName": "Centro Comercial Satélite",
        "supplierId": "PROV-01",
        "supplierName": "Constructora del Valle S.A. de C.V.",
        "concept": "Estructura metálica — nivel 3",
        "grossAmount": "4200000.00",
        "amortization": "420000.00",
        "guaranteeFund": "210000.00",
        "netAmount": "3570000.00",
        "date": "2026-05-16T10:00:00Z",
        "status": "rechazada",
        "contractProgress": {
            "totalAmount": "32000000.00",
            "exercisedAmount": "9600000.00",
            "remainingAmount": "22400000.00",
            "percentage": 30,
        },
        "authorizationSteps": [
            {
                "userId": "USR-002",
                "userName": "Ana Lucía Garza",
                "status": "rechazada",
                "date": "2026-05-17T11:00:00Z",
                "comment": "Revisar desglose de partidas. La amortización no corresponde "
                "al anticipo entregado.",
            },
        ],
    },
    {
        "id": "EST-005",
        "projectId": "PRY-102",
        "projectName": "Residencial Bosques",
        "supplierId": "PROV-04",
        "supplierName": "Plomería Industrial del Norte",
        "concept": "Instalación hidráulica general",
        "grossAmount": "720000.00",
        "amortization": "72000.00",
        "guaranteeFund": "36000.00",
        "netAmount": "612000.00",
        "date": "2026-05-08T08:30:00Z",
        "status": "recepcionada",
        "contractProgress": {
            "totalAmount": "4500000.00",
            "exercisedAmount": "4500000.00",
            "remainingAmount": "0.00",
            "percentage": 100,
        },
        "authorizationSteps": [
            {
                "userId": "USR-001",
                "userName": "Carlos Mendoza",
                "status": "autorizada",
                "date": "2026-05-09T09:15:00Z",
            },
            {
                "userId": "USR-003",
                "userName": "Roberto Sánchez",
                "status": "autorizada",
                "date": "2026-05-10T14:20:00Z",
            },
        ],
    },
    {
        "id": "EST-006",
        "projectId": "PRY-103",
        "projectName": "Centro Comercial Satélite",
        "supplierId": "PROV-05",
        "supplierName": "Vidrios y Cancelería Moderna",
        "concept": "Fachada de cristal templado",
        "grossAmount": "2850000.00",
        "amortization": "285000.00",
        "guaranteeFund": "142500.00",
        "netAmount": "2422500.00",
        "date": "2026-05-22T16:00:00Z",
        "status": "sin_autorizacion",
        "contractProgress": {
            "totalAmount": "8500000.00",
            "exercisedAmount": "2550000.00",
            "remainingAmount": "5950000.00",
            "percentage": 30,
        },
        "authorizationSteps": [
            {
                "userId": "USR-001",
                "userName": "Carlos Mendoza",
                "status": "sin_autorizacion",
                "date": None,
            },
            {
                "userId": "USR-002",
                "userName": "Ana Lucía Garza",
                "status": "sin_autorizacion",
                "date": None,
            },
        ],
    },
    {
        "id": "EST-007",
        "projectId": "PRY-101",
        "projectName": "Torre Reforma 500",
        "supplierId": "PROV-06",
        "supplierName": "Impermeabilizantes Nacionales",
        "concept": "Impermeabilización de azotea",
        "grossAmount": "480000.00",
        "amortization": "48000.00",
        "guaranteeFund": "24000.00",
        "netAmount": "408000.00",
        "date": "2026-05-24T12:00:00Z",
        "status": "autorizada_parcialmente",
        "contractProgress": {
            "totalAmount": "1500000.00",
            "exercisedAmount": "480000.00",
            "remainingAmount": "1020000.00",
            "percentage": 32,
        },
        "authorizationSteps": [
            {
                "userId": "USR-001",
                "userName": "Carlos Mendoza",
                "status": "autorizada",
                "date": "2026-05-25T08:00:00Z",
            },
            {
                "userId": "USR-003",
                "userName": "Roberto Sánchez",
                "status": "sin_autorizacion",
                "date": None,
            },
        ],
    },
]

RAW_PAYMENTS: list[dict] = [
    {
        "id": "PAG-001",
        "description": "Renta de grúa torre — mayo 2026",
        "amount": "285000.00",
        "date": "2026-05-20T09:00:00Z",
        "status": "sin_autorizacion",
        "projectId": "PRY-101",
        "projectName": "Torre Reforma 500",
        "supplierId": "PROV-07",
        "supplierName": "Maquinaria Pesada del Centro",
        "authorizationSteps": [
            {
                "userId": "USR-001",
                "userName": "Carlos Mendoza",
                "status": "sin_autorizacion",
                "date": None,
            },
            {
                "userId": "USR-002",
                "userName": "Ana Lucía Garza",
                "status": "sin_autorizacion",
                "date": None,
            },
        ],
    },
    {
        "id": "PAG-002",
        "description": "Servicio de topografía — levantamiento final",
        "amount": "45000.00",
        "date": "2026-05-18T11:00:00Z",
        "status": "autorizada",
        "projectId": "PRY-102",
        "projectName": "Residencial Bosques",
        "supplierId": "PROV-08",
        "supplierName": "Topografía Precisa S.C.",
        "authorizationSteps": [
            {
                "userId": "USR-001",
                "userName": "Carlos Mendoza",
                "status": "autorizada",
                "date": "2026-05-19T08:30:00Z",
            },
        ],
    },
    {
        "id": "PAG-003",
        "description": "Suministro de concreto premezclado — 120m³",
        "amount": "192000.00",
        "date": "2026-05-17T14:30:00Z",
        "status": "autorizada_parcialmente",
        "projectId": "PRY-103",
        "projectName": "Centro Comercial Satélite",
        "supplierId": "PROV-09",
        "supplierName": "Concretos y Agregados Nacional",
        "authorizationSteps": [
            {
                "userId": "USR-002",
                "userName": "Ana Lucía Garza",
                "status": "autorizada",
                "date": "2026-05-18T09:00:00Z",
            },
            {
                "userId": "USR-003",
                "userName": "Roberto Sánchez",
                "status": "sin_autorizacion",
                "date": None,
            },
        ],
    },
    {
        "id": "PAG-004",
        "description": "Análisis de laboratorio — resistencia de concreto",
        "amount": "28500.00",
        "date": "2026-05-15T10:00:00Z",
        "status": "rechazada",
        "projectId": "PRY-101",
        "projectName": "Torre Reforma 500",
        "supplierId": "PROV-10",
        "supplierName": "Laboratorio de Materiales Central",
        "authorizationSteps": [
            {
                "userId": "USR-001",
                "userName": "Carlos Mendoza",
                "status": "rechazada",
                "date": "2026-05-16T11:15:00Z",
                "comment": "Cotización más alta que el presupuesto aprobado. "
                "Solicitar nueva cotización.",
            },
        ],
    },
    {
        "id": "PAG-005",
        "description": "Vigilancia de obra — mayo 2026",
        "amount": "65000.00",
        "date": "2026-05-01T08:00:00Z",
        "status": "recepcionada",
        "projectId": "PRY-102",
        "projectName": "Residencial Bosques",
        "supplierId": "PROV-11",
        "supplierName": "Seguridad Integral MX",
        "authorizationSteps": [
            {
                "userId": "USR-001",
                "userName": "Carlos Mendoza",
                "status": "autorizada",
                "date": "2026-05-02T09:00:00Z",
            },
            {
                "userId": "USR-002",
                "userName": "Ana Lucía Garza",
                "status": "autorizada",
                "date": "2026-05-03T15:30:00Z",
            },
        ],
    },
    {
        "id": "PAG-006",
        "description": "Transporte de materiales — viaje especial",
        "amount": "38000.00",
        "date": "2026-05-22T13:00:00Z",
        "status": "sin_autorizacion",
        "projectId": "PRY-103",
        "projectName": "Centro Comercial Satélite",
        "supplierId": "PROV-12",
        "supplierName": "Fletes y Logística Express",
        "authorizationSteps": [
            {
                "userId": "USR-001",
                "userName": "Carlos Mendoza",
                "status": "sin_autorizacion",
                "date": None,
            },
        ],
    },
    {
        "id": "PAG-007",
        "description": "Señalización y seguridad industrial",
        "amount": "22000.00",
        "date": "2026-05-23T16:00:00Z",
        "status": "sin_autorizacion",
        "projectId": "PRY-101",
        "projectName": "Torre Reforma 500",
        "supplierId": "PROV-13",
        "supplierName": "Equipos de Seguridad Pro",
        "authorizationSteps": [
            {
                "userId": "USR-002",
                "userName": "Ana Lucía Garza",
                "status": "sin_autorizacion",
                "date": None,
            },
            {
                "userId": "USR-001",
                "userName": "Carlos Mendoza",
                "status": "sin_autorizacion",
                "date": None,
            },
        ],
    },
    {
        "id": "PAG-008",
        "description": "Licencias y permisos municipales",
        "amount": "156000.00",
        "date": "2026-05-10T10:00:00Z",
        "status": "autorizada",
        "projectId": "PRY-103",
        "projectName": "Centro Comercial Satélite",
        "supplierId": "PROV-14",
        "supplierName": "Gestoría Legal y Administrativa",
        "authorizationSteps": [
            {
                "userId": "USR-003",
                "userName": "Roberto Sánchez",
                "status": "autorizada",
                "date": "2026-05-11T08:00:00Z",
            },
            {
                "userId": "USR-001",
                "userName": "Carlos Mendoza",
                "status": "autorizada",
                "date": "2026-05-12T14:45:00Z",
            },
        ],
    },
]

RAW_PAYMENT_ORDERS: list[dict] = [
    {
        "id": "OP-001",
        "concept": "Pago estimación 1 — Obra civil, cimentación profunda",
        "amount": "2975000.00",
        "date": "2026-05-21T09:00:00Z",
        "dueDate": "2026-06-05T00:00:00Z",
        "paymentMethod": "transfer",
        "relatedEstimateId": "EST-001",
        "status": "sin_autorizacion",
        "projectId": "PRY-101",
        "projectName": "Torre Reforma 500",
        "supplierId": "PROV-01",
        "supplierName": "Constructora del Valle S.A. de C.V.",
        "authorizationSteps": [
            {
                "userId": "USR-001",
                "userName": "Carlos Mendoza",
                "status": "sin_autorizacion",
                "date": None,
            },
            {
                "userId": "USR-002",
                "userName": "Ana Lucía Garza",
                "status": "sin_autorizacion",
                "date": None,
            },
        ],
    },
    {
        "id": "OP-002",
        "concept": "Pago estimación 2 — Suministro de acero estructural",
        "amount": "1530000.00",
        "date": "2026-05-19T11:30:00Z",
        "dueDate": "2026-06-02T00:00:00Z",
        "paymentMethod": "transfer",
        "relatedEstimateId": "EST-002",
        "status": "autorizada_parcialmente",
        "projectId": "PRY-101",
        "projectName": "Torre Reforma 500",
        "supplierId": "PROV-02",
        "supplierName": "Aceros y Materiales Monterrey",
        "authorizationSteps": [
            {
                "userId": "USR-001",
                "userName": "Carlos Mendoza",
                "status": "autorizada",
                "date": "2026-05-20T08:45:00Z",
            },
            {
                "userId": "USR-002",
                "userName": "Ana Lucía Garza",
                "status": "sin_autorizacion",
                "date": None,
            },
        ],
    },
    {
        "id": "OP-003",
        "concept": "Pago estimación 3 — Instalación eléctrica fase 2",
        "amount": "807500.00",
        "date": "2026-05-14T14:00:00Z",
        "dueDate": "2026-05-28T00:00:00Z",
        "paymentMethod": "check",
        "relatedEstimateId": "EST-003",
        "status": "autorizada",
        "projectId": "PRY-102",
        "projectName": "Residencial Bosques",
        "supplierId": "PROV-03",
        "supplierName": "Instalaciones Eléctricas MX",
        "authorizationSteps": [
            {
                "userId": "USR-001",
                "userName": "Carlos Mendoza",
                "status": "autorizada",
                "date": "2026-05-15T09:00:00Z",
            },
            {
                "userId": "USR-002",
                "userName": "Ana Lucía Garza",
                "status": "autorizada",
                "date": "2026-05-16T16:30:00Z",
            },
        ],
    },
    {
        "id": "OP-004",
        "concept": "Pago estimación 4 — Estructura metálica nivel 3",
        "amount": "3570000.00",
        "date": "2026-05-18T10:00:00Z",
        "dueDate": "2026-06-01T00:00:00Z",
        "paymentMethod": "transfer",
        "relatedEstimateId": "EST-004",
        "status": "rechazada",
        "projectId": "PRY-103",
        "projectName": "Centro Comercial Satélite",
        "supplierId": "PROV-01",
        "supplierName": "Constructora del Valle S.A. de C.V.",
        "authorizationSteps": [
            {
                "userId": "USR-002",
                "userName": "Ana Lucía Garza",
                "status": "rechazada",
                "date": "2026-05-19T11:00:00Z",
                "comment": "La estimación asociada fue rechazada. No procede el pago "
                "hasta corregir el desglose.",
            },
        ],
    },
    {
        "id": "OP-005",
        "concept": "Pago estimación 5 — Instalación hidráulica general",
        "amount": "612000.00",
        "date": "2026-05-09T08:30:00Z",
        "dueDate": "2026-05-23T00:00:00Z",
        "paymentMethod": "transfer",
        "relatedEstimateId": "EST-005",
        "status": "recepcionada",
        "projectId": "PRY-102",
        "projectName": "Residencial Bosques",
        "supplierId": "PROV-04",
        "supplierName": "Plomería Industrial del Norte",
        "authorizationSteps": [
            {
                "userId": "USR-001",
                "userName": "Carlos Mendoza",
                "status": "autorizada",
                "date": "2026-05-10T09:15:00Z",
            },
            {
                "userId": "USR-003",
                "userName": "Roberto Sánchez",
                "status": "autorizada",
                "date": "2026-05-11T14:20:00Z",
            },
        ],
    },
    {
        "id": "OP-006",
        "concept": "Anticipo de contrato — Fachada de cristal templado",
        "amount": "855000.00",
        "date": "2026-05-23T16:00:00Z",
        "dueDate": "2026-06-08T00:00:00Z",
        "paymentMethod": "check",
        "relatedEstimateId": None,
        "status": "sin_autorizacion",
        "projectId": "PRY-103",
        "projectName": "Centro Comercial Satélite",
        "supplierId": "PROV-05",
        "supplierName": "Vidrios y Cancelería Moderna",
        "authorizationSteps": [
            {
                "userId": "USR-001",
                "userName": "Carlos Mendoza",
                "status": "sin_autorizacion",
                "date": None,
            },
            {
                "userId": "USR-002",
                "userName": "Ana Lucía Garza",
                "status": "sin_autorizacion",
                "date": None,
            },
        ],
    },
]
